### Deal with Dataframe (tidy up)

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("assignment-01-data-unformated.xlsx", header=[0, 1], skipinitialspace=True)
df

       Unnamed: 0_level_0 Unnamed: 1_level_0 soft corals                  \
name            longitude           latitude        2017    2016    2015
site01            143.515            -11.843      0.8387  0.8021  0.7534
site02            147.898             18.937      0.2123  0.1923  0.1721
site03            144.081            -10.321      0.7534  0.6023  0.3721
site04            150.444            -20.414      0.1245  0.1178  0.1134
site05            143.786            -13.107      0.9423  0.9123  0.7623
site06            146.589            -17.981         NaN     NaN     NaN
site07            145.043            -14.383      0.6789  0.6078  0.5876
site08            145.715            -16.091      0.6523  0.6321  0.6012

                                                 ...   hard corals          \
name      2014    2013    2012    2011    2010   ...          2011    2010
site01  0.7499  0.5770  0.5643  0.5543  0.5629   ...        0.1934     NaN
site02  0.1578  0.1480     NaN     NaN     NaN   ...           NaN     NaN
site03  0.2689  0.2589     NaN     NaN     NaN   ...           NaN     NaN
site04  0.1098  0.1089  0.1067  0.1023  0.1001   ...        0.1597  0.1595
site05  0.6023  0.3023  0.2845  0.2913  0.1445   ...           NaN     NaN
site06     NaN     NaN     NaN     NaN     NaN   ...           NaN     NaN
site07  0.5645  0.5512  0.4012  0.3998  0.4034   ...        0.1503     NaN
site08  0.6003  0.5889     NaN     NaN     NaN   ...           NaN     NaN

       sea pens
name       2017    2016     2015    2014    2013    2012    2011    2010
site01   0.1578  0.1265  0.12450  0.1076  0.0876  0.0851  0.0812  0.0533
site02   0.8013  0.7012  0.30890  0.2948  0.2890  0.2861     NaN     NaN
site03   0.0934  0.0912  0.09012  0.0901  0.0879  0.0859     NaN     NaN
site04   0.4123  0.3823  0.36210  0.3412  0.3076  0.2918  0.2901  0.2699
site05   0.3723  0.3612  0.36100  0.3534  0.3512  0.3479  0.3467  0.3019
site06   0.6787  0.6034  0.59230  0.5256  0.5023  0.4911  0.4901  0.4798
site07   0.4012  0.3834  0.36780  0.3467  0.3248  0.3035  0.3010  0.2556
site08   0.3900  0.1045  0.04340  0.0419  0.0389  0.0371     NaN     NaN

[8 rows x 42 columns]

In [3]:
df_drop_loc = df.drop(['Unnamed: 0_level_0', 'Unnamed: 1_level_0'], axis=1)
df_drop_loc

/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:3111: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

       soft corals                                                          \
name          2017    2016    2015    2014    2013    2012    2011    2010
site01      0.8387  0.8021  0.7534  0.7499  0.5770  0.5643  0.5543  0.5629
site02      0.2123  0.1923  0.1721  0.1578  0.1480     NaN     NaN     NaN
site03      0.7534  0.6023  0.3721  0.2689  0.2589     NaN     NaN     NaN
site04      0.1245  0.1178  0.1134  0.1098  0.1089  0.1067  0.1023  0.1001
site05      0.9423  0.9123  0.7623  0.6023  0.3023  0.2845  0.2913  0.1445
site06         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
site07      0.6789  0.6078  0.5876  0.5645  0.5512  0.4012  0.3998  0.4034
site08      0.6523  0.6321  0.6012  0.6003  0.5889     NaN     NaN     NaN

       sea fans           ...   hard corals         sea pens                   \
name       2017    2016   ...          2011    2010     2017    2016     2015
site01   0.4732  0.4712   ...        0.1934     NaN   0.1578  0.1265  0.12450
site02   0.5632  0.5432   ...           NaN     NaN   0.8013  0.7012  0.30890
site03   0.7523  0.5021   ...           NaN     NaN   0.0934  0.0912  0.09012
site04   0.7789  0.6523   ...        0.1597  0.1595   0.4123  0.3823  0.36210
site05   0.4834  0.4623   ...           NaN     NaN   0.3723  0.3612  0.36100
site06   0.8645  0.7564   ...           NaN     NaN   0.6787  0.6034  0.59230
site07      NaN     NaN   ...        0.1503     NaN   0.4012  0.3834  0.36780
site08   0.4823  0.4532   ...           NaN     NaN   0.3900  0.1045  0.04340


name      2014    2013    2012    2011    2010
site01  0.1076  0.0876  0.0851  0.0812  0.0533
site02  0.2948  0.2890  0.2861     NaN     NaN
site03  0.0901  0.0879  0.0859     NaN     NaN
site04  0.3412  0.3076  0.2918  0.2901  0.2699
site05  0.3534  0.3512  0.3479  0.3467  0.3019
site06  0.5256  0.5023  0.4911  0.4901  0.4798
site07  0.3467  0.3248  0.3035  0.3010  0.2556
site08  0.0419  0.0389  0.0371     NaN     NaN

[8 rows x 40 columns]

In [4]:
new_df = df_drop_loc.stack()
new_df

             blue corals  hard corals  sea fans  sea pens  soft corals
       name
site01 2010     0.397800          NaN    0.3734   0.05330       0.5629
       2011     0.402500       0.1934    0.3912   0.08120       0.5543
       2012     0.503700       0.2045    0.3856   0.08510       0.5643
       2013     0.519800       0.3998    0.4088   0.08760       0.5770
       2014     0.589800       0.4078    0.4134   0.10760       0.7499
       2015     0.621300       0.4099    0.4687   0.12450       0.7534
       2016     0.656100       0.4178    0.4712   0.12650       0.8021
       2017     0.682300       0.4432    0.4732   0.15780       0.8387
site02 2012          NaN       0.2482    0.4598   0.28610          NaN
       2013     0.173700       0.2477    0.4639   0.28900       0.1480
       2014     0.177900       0.2489    0.4850   0.29480       0.1578
       2015     0.187800       0.2532    0.5021   0.30890       0.1721
       2016     0.213400       0.3012    0.5432   0.70120       0.1923
       2017     0.232100       0.3489    0.5632   0.80130       0.2123
site03 2012          NaN       0.1733    0.0634   0.08590          NaN
       2013          NaN       0.1765    0.0828   0.08790       0.2589
       2014          NaN       0.1844    0.1045   0.09010       0.2689
       2015          NaN       0.1834    0.3245   0.09012       0.3721
       2016          NaN       0.3056    0.5021   0.09120       0.6023
       2017          NaN       0.7134    0.7523   0.09340       0.7534
site04 2010     0.267100       0.1595    0.2278   0.26990       0.1001
       2011     0.269200       0.1597    0.2345   0.29010       0.1023
       2012     0.278700       0.1689    0.2512   0.29180       0.1067
       2013     0.287600       0.1723    0.2698   0.30760       0.1089
       2014     0.291200       0.2343    0.2767   0.34120       0.1098
       2015     0.301200       0.3280    0.3078   0.36210       0.1134
       2016     0.324500       0.4023    0.6523   0.38230       0.1178
       2017     0.370000       0.6798    0.7789   0.41230       0.1245
site05 2010     0.491900          NaN    0.3765   0.30190       0.1445
       2011     0.496700          NaN    0.3899   0.34670       0.2913
       2012     0.498700          NaN    0.3978   0.34790       0.2845
       2013     0.500200          NaN    0.4010   0.35120       0.3023
       2014     0.501200          NaN    0.4012   0.35340       0.6023
       2015     0.512300          NaN    0.4223   0.36100       0.7623
       2016     0.562300          NaN    0.4623   0.36120       0.9123
       2017     0.572300          NaN    0.4834   0.37230       0.9423
site06 2010     0.128700          NaN    0.4021   0.47980          NaN
       2011     0.136500          NaN    0.4137   0.49010          NaN
       2012     0.139500          NaN    0.5034   0.49110          NaN
       2013     0.159700          NaN    0.5537   0.50230          NaN
       2014     0.164500          NaN    0.5834   0.52560          NaN
       2015     0.178700          NaN    0.6075   0.59230          NaN
       2016     0.184500          NaN    0.7564   0.60340          NaN
       2017     0.205600          NaN    0.8645   0.67870          NaN
site07 2010     0.459900          NaN       NaN   0.25560       0.4034
       2011     0.467800       0.1503       NaN   0.30100       0.3998
       2012     0.456700       0.1499       NaN   0.30350       0.4012
       2013     0.004696       0.1545       NaN   0.32480       0.5512
       2014     0.473200       0.1689       NaN   0.34670       0.5645
       2015     0.481200       0.1823       NaN   0.36780       0.5876
       2016     0.488900       0.2576       NaN   0.38340       0.6078
       2017     0.492100       0.3212       NaN   0.40120       0.6789
site08 2012          NaN       0.1310    0.3245   0.03710          NaN
       2013     0.399300       0.1384    0.3866   0.03890       0.5889
       2014     0.407800       1.4880    0.3984   0.04190       0.6003
       2015     0.409800       0.1456    0.4089   0.04340       0.6012
       2016     0.432100       0.1556    0.4532   0.10450       0.6321
       2017     0.453200       0.2045    0.4823   0.39000       0.6523

In [5]:
new_df.reset_index(level=[0,1], inplace=True)

In [6]:
final_df = new_df.rename(index=str, columns={"level_0":"site", "name":"year"})
final_df

      site  year  blue corals  hard corals  sea fans  sea pens  soft corals
0   site01  2010     0.397800          NaN    0.3734   0.05330       0.5629
1   site01  2011     0.402500       0.1934    0.3912   0.08120       0.5543
2   site01  2012     0.503700       0.2045    0.3856   0.08510       0.5643
3   site01  2013     0.519800       0.3998    0.4088   0.08760       0.5770
4   site01  2014     0.589800       0.4078    0.4134   0.10760       0.7499
5   site01  2015     0.621300       0.4099    0.4687   0.12450       0.7534
6   site01  2016     0.656100       0.4178    0.4712   0.12650       0.8021
7   site01  2017     0.682300       0.4432    0.4732   0.15780       0.8387
8   site02  2012          NaN       0.2482    0.4598   0.28610          NaN
9   site02  2013     0.173700       0.2477    0.4639   0.28900       0.1480
10  site02  2014     0.177900       0.2489    0.4850   0.29480       0.1578
11  site02  2015     0.187800       0.2532    0.5021   0.30890       0.1721
12  site02  2016     0.213400       0.3012    0.5432   0.70120       0.1923
13  site02  2017     0.232100       0.3489    0.5632   0.80130       0.2123
14  site03  2012          NaN       0.1733    0.0634   0.08590          NaN
15  site03  2013          NaN       0.1765    0.0828   0.08790       0.2589
16  site03  2014          NaN       0.1844    0.1045   0.09010       0.2689
17  site03  2015          NaN       0.1834    0.3245   0.09012       0.3721
18  site03  2016          NaN       0.3056    0.5021   0.09120       0.6023
19  site03  2017          NaN       0.7134    0.7523   0.09340       0.7534
20  site04  2010     0.267100       0.1595    0.2278   0.26990       0.1001
21  site04  2011     0.269200       0.1597    0.2345   0.29010       0.1023
22  site04  2012     0.278700       0.1689    0.2512   0.29180       0.1067
23  site04  2013     0.287600       0.1723    0.2698   0.30760       0.1089
24  site04  2014     0.291200       0.2343    0.2767   0.34120       0.1098
25  site04  2015     0.301200       0.3280    0.3078   0.36210       0.1134
26  site04  2016     0.324500       0.4023    0.6523   0.38230       0.1178
27  site04  2017     0.370000       0.6798    0.7789   0.41230       0.1245
28  site05  2010     0.491900          NaN    0.3765   0.30190       0.1445
29  site05  2011     0.496700          NaN    0.3899   0.34670       0.2913
30  site05  2012     0.498700          NaN    0.3978   0.34790       0.2845
31  site05  2013     0.500200          NaN    0.4010   0.35120       0.3023
32  site05  2014     0.501200          NaN    0.4012   0.35340       0.6023
33  site05  2015     0.512300          NaN    0.4223   0.36100       0.7623
34  site05  2016     0.562300          NaN    0.4623   0.36120       0.9123
35  site05  2017     0.572300          NaN    0.4834   0.37230       0.9423
36  site06  2010     0.128700          NaN    0.4021   0.47980          NaN
37  site06  2011     0.136500          NaN    0.4137   0.49010          NaN
38  site06  2012     0.139500          NaN    0.5034   0.49110          NaN
39  site06  2013     0.159700          NaN    0.5537   0.50230          NaN
40  site06  2014     0.164500          NaN    0.5834   0.52560          NaN
41  site06  2015     0.178700          NaN    0.6075   0.59230          NaN
42  site06  2016     0.184500          NaN    0.7564   0.60340          NaN
43  site06  2017     0.205600          NaN    0.8645   0.67870          NaN
44  site07  2010     0.459900          NaN       NaN   0.25560       0.4034
45  site07  2011     0.467800       0.1503       NaN   0.30100       0.3998
46  site07  2012     0.456700       0.1499       NaN   0.30350       0.4012
47  site07  2013     0.004696       0.1545       NaN   0.32480       0.5512
48  site07  2014     0.473200       0.1689       NaN   0.34670       0.5645
49  site07  2015     0.481200       0.1823       NaN   0.36780       0.5876
50  site07  2016     0.488900       0.2576       NaN   0.38340       0.6078
51  site07  2017     0.492100       0.3212       NaN   0.40120       0.6789
52  site08  2012          NaN       0.1310    0.3245   0.03710          NaN
53  site08  2013     0.399300       0.1384    0.3866   0.03890       0.5889
54  site08  2014     0.407800       1.4880    0.3984   0.04190       0.6003
55  site08  2015     0.409800       0.1456    0.4089   0.04340       0.6012
56  site08  2016     0.432100       0.1556    0.4532   0.10450       0.6321
57  site08  2017     0.453200       0.2045    0.4823   0.39000       0.6523

In [7]:
final_df.to_excel("result1.xlsx")

### Deal with Location

In [11]:
final_df.loc[final_df['site'] == 'site01', 'longitude'] = 143.515
final_df.loc[final_df['site'] == 'site02', 'longitude'] = 147.898
final_df.loc[final_df['site'] == 'site03', 'longitude'] = 144.081
final_df.loc[final_df['site'] == 'site04', 'longitude'] = 150.444
final_df.loc[final_df['site'] == 'site05', 'longitude'] = 143.786
final_df.loc[final_df['site'] == 'site06', 'longitude'] = 146.589
final_df.loc[final_df['site'] == 'site07', 'longitude'] = 145.043
final_df.loc[final_df['site'] == 'site08', 'longitude'] = 145.715

final_df.loc[final_df['site'] == 'site01', 'latitude'] = -11.843
final_df.loc[final_df['site'] == 'site02', 'latitude'] = 18.937
final_df.loc[final_df['site'] == 'site03', 'latitude'] = -10.321
final_df.loc[final_df['site'] == 'site04', 'latitude'] = -20.414
final_df.loc[final_df['site'] == 'site05', 'latitude'] = -13.107
final_df.loc[final_df['site'] == 'site06', 'latitude'] = -17.981
final_df.loc[final_df['site'] == 'site07', 'latitude'] = -14.383
final_df.loc[final_df['site'] == 'site08', 'latitude'] = -16.091

In [12]:
final_df

,site,year,blue corals,hard corals,sea fans,sea pens,soft corals,longitude,latitude
0,site01,2010,0.397800,NaN,0.3734,0.05330,0.5629,143.515,-11.843
1,site01,2011,0.402500,0.1934,0.3912,0.08120,0.5543,143.515,-11.843
2,site01,2012,0.503700,0.2045,0.3856,0.08510,0.5643,143.515,-11.843
3,site01,2013,0.519800,0.3998,0.4088,0.08760,0.5770,143.515,-11.843
4,site01,2014,0.589800,0.4078,0.4134,0.10760,0.7499,143.515,-11.843
5,site01,2015,0.621300,0.4099,0.4687,0.12450,0.7534,143.515,-11.843
6,site01,2016,0.656100,0.4178,0.4712,0.12650,0.8021,143.515,-11.843
7,site01,2017,0.682300,0.4432,0.4732,0.15780,0.8387,143.515,-11.843
8,site02,2012,NaN,0.2482,0.4598,0.28610,NaN,147.898,18.937
9,site02,2013,0.173700,0.2477,0.4639,0.28900,0.1480,147.898,18.937
10,site02,2014,0.177900,0.2489,0.4850,0.29480,0.1578,147.898,18.937
11,site02,2015,0.187800,0.2532,0.5021,0.30890,0.1721,147.898,18.937
12,site02,2016,0.213400,0.3012,0.5432,0.70120,0.1923,147.898,18.937
13,site02,2017,0.232100,0.3489,0.5632,0.80130,0.2123,147.898,18.937
14,site03,2012,NaN,0.1733,0.0634,0.08590,NaN,144.081,-10.321
15,site03,2013,NaN,0.1765,0.0828,0.08790,0.2589,144.081,-10.321
16,site03,2014,NaN,0.1844,0.1045,0.09010,0.2689,144.081,-10.321
17,site03,2015,NaN,0.1834,0.3245,0.09012,0.3721,144.081,-10.321
18,site03,2016,NaN,0.3056,0.5021,0.09120,0.6023,144.081,-10.321
19,site03,2017,NaN,0.7134,0.7523,0.09340,0.7534,144.081,-10.321
20,site04,2010,0.267100,0.1595,0.2278,0.26990,0.1001,150.444,-20.414
21,site04,2011,0.269200,0.1597,0.2345,0.29010,0.1023,150.444,-20.414
22,site04,2012,0.278700,0.1689,0.2512,0.29180,0.1067,150.444,-20.414
23,site04,2013,0.287600,0.1723,0.2698,0.30760,0.1089,150.444,-20.414
24,site04,2014,0.291200,0.2343,0.2767,0.34120,0.1098,150.444,-20.414
25,site04,2015,0.301200,0.3280,0.3078,0.36210,0.1134,150.444,-20.414
26,site04,2016,0.324500,0.4023,0.6523,0.38230,0.1178,150.444,-20.414
27,site04,2017,0.370000,0.6798,0.7789,0.41230,0.1245,150.444,-20.414
28,site05,2010,0.491900,NaN,0.3765,0.30190,0.1445,143.786,-13.107
29,site05,2011,0.496700,NaN,0.3899,0.34670,0.2913,143.786,-13.107
30,site05,2012,0.498700,NaN,0.3978,0.34790,0.2845,143.786,-13.107
31,site05,2013,0.500200,NaN,0.4010,0.35120,0.3023,143.786,-13.107
32,site05,2014,0.501200,NaN,0.4012,0.35340,0.6023,143.786,-13.107
33,site05,2015,0.512300,NaN,0.4223,0.36100,0.7623,143.786,-13.107
34,site05,2016,0.562300,NaN,0.4623,0.36120,0.9123,143.786,-13.107
35,site05,2017,0.572300,NaN,0.4834,0.37230,0.9423,143.786,-13.107
36,site06,2010,0.128700,NaN,0.4021,0.47980,NaN,146.589,-17.981
37,site06,2011,0.136500,NaN,0.4137,0.49010,NaN,146.589,-17.981
38,site06,2012,0.139500,NaN,0.5034,0.49110,NaN,146.589,-17.981
39,site06,2013,0.159700,NaN,0.5537,0.50230,NaN,146.589,-17.981
40,site06,2014,0.164500,NaN,0.5834,0.52560,NaN,146.589,-17.981
41,site06,2015,0.178700,NaN,0.6075,0.59230,NaN,146.589,-17.981
42,site06,2016,0.184500,NaN,0.7564,0.60340,NaN,146.589,-17.981
43,site06,2017,0.205600,NaN,0.8645,0.67870,NaN,146.589,-17.981
44,site07,2010,0.459900,NaN,NaN,0.25560,0.4034,145.043,-14.383
45,site07,2011,0.467800,0.1503,NaN,0.30100,0.3998,145.043,-14.383
46,site07,2012,0.456700,0.1499,NaN,0.30350,0.4012,145.043,-14.383
47,site07,2013,0.004696,0.1545,NaN,0.32480,0.5512,145.043,-14.383
48,site07,2014,0.473200,0.1689,NaN,0.34670,0.5645,145.043,-14.383
49,site07,2015,0.481200,0.1823,NaN,0.36780,0.5876,145.043,-14.383
50,site07,2016,0.488900,0.2576,NaN,0.38340,0.6078,145.043,-14.383
51,site07,2017,0.492100,0.3212,NaN,0.40120,0.6789,145.043,-14.383
52,site08,2012,NaN,0.1310,0.3245,0.03710,NaN,145.715,-16.091
53,site08,2013,0.399300,0.1384,0.3866,0.03890,0.5889,145.715,-16.091
54,site08,2014,0.407800,1.4880,0.3984,0.04190,0.6003,145.715,-16.091
55,site08,2015,0.409800,0.1456,0.4089,0.04340,0.6012,145.715,-16.091
56,site08,2016,0.432100,0.1556,0.4532,0.10450,0.6321,145.715,-16.091
57,site08,2017,0.453200,0.2045,0.4823,0.39000,0.6523,145.715,-16.091